### ISSUE TITLE
Binary Releases

### ISSUE THREAD

**Issue by boonkerz** [smasherprog/rat_lite#73]
is it possible to publish binary releases for windows/mac from the build service?

**Comment by smasherprog** [comment]
It is something that I am going to do within the next few weeks.

**Comment by boonkerz** [comment]
dyld: Library not loaded: @rpath/libjpeg.62.dylib
  Referenced from: /Users/thomas/projekte/Remote_Access_Library/build/src/server/./rat_server
  Reason: image not found
[1]    28799 abort      ./rat_server

Any Idea?

**Comment by smasherprog** [comment]
I havent tested much on mac other than periodically.
It should be just that the dylib is not in the same folder as the executable. Try moving it there and ill test this when I get home today to make sure all the files are copied correctly to the same location as the executable

**Comment by smasherprog** [comment]
I just tried setting up an xcode project and I cant get it to build.
I was successful when building a static library through the command line using
cmake -DBUILD_SHARED_LIBS=OFF -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl .. && make

**Comment by smasherprog** [comment]
I just tried setting up an xcode project and I cant get it to build.
I was successful when building a static library through the command line using
cmake -DBUILD_SHARED_LIBS=OFF -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl .. && make

**Comment by smasherprog** [comment]
Ill try to get the xcode project to be created using cmake.. its close, but the lib-jpeg turbo project needs some configuration

**Comment by boonkerz** [comment]
yea with LIBS=OFF the server works. thx

**Comment by smasherprog** [comment]
I should be able to get the mac xcode cmake project generation working today as well.

**Comment by smasherprog** [comment]
Ill also fix this issue with the shared vs static libs

**Comment by smasherprog** [comment]
The library should build across win, linux and mac now.
You can generate an xcode project as well using cmake -G XCode  -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl

Ill work on binaries being automatically uploaded as part of the build process
