### ISSUE TITLE
Why m getting this error

### ISSUE THREAD

**Issue by ch3than** [smasherprog/rat_lite#74]
im on kali

-- Found LIBJPEGTURBO: /usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/libturbojpeg.so  
-- Found LIBJPEGTURBO: /usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/libturbojpeg.so;/usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/libturbojpeg.so  
-- 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_XTest_LIB (ADVANCED)
    linked by target "rat_lite" in directory /root/rat_lite
    linked by target "rat_server" in directory /root/rat_lite/src/server
    linked by target "rat_test" in directory /root/rat_lite/test
X11_Xinerama_LIB (ADVANCED)
    linked by target "rat_lite" in directory /root/rat_lite
    linked by target "rat_server" in directory /root/rat_lite/src/server
    linked by target "rat_test" in directory /root/rat_lite/test

**Comment by smasherprog** [comment]
https://github.com/smasherprog/rat_lite/blob/master/README.md#libraries
