### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by ch3than** [smasherprog/rat_lite#75]
[ 78%] Building CXX object CMakeFiles/rat_lite.dir/src/ClientDriver.cpp.o
In file included from /root/rat_lite/src/ClientDriver.cpp:2:0:
/usr/include/c++/7/bits/sstream.tcc: In member function ‘virtual std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::int_type std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::overflow(std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::int_type)’:
/usr/include/c++/7/bits/sstream.tcc:129:39: error: expected unqualified-id before ‘(’ token
    const __size_type __opt_len = std::max(__size_type(2 * __capacity),
                                       ^
/root/rat_lite/src/ClientDriver.cpp: In member function ‘void SL::RAT_Lite::ClientDriver::Frame(const unsigned char*, size_t, CALLBACKTYPE&&)’:
/root/rat_lite/src/ClientDriver.cpp:98:17: error: there are no arguments to ‘tjDecompressHeader2’ that depend on a template parameter, so a declaration of ‘tjDecompressHeader2’ must be available [-fpermissive]
             if (tjDecompressHeader2(jpegDecompressor, src, static_cast<unsigned long>(len), &outwidth, &outheight, &jpegSubsamp) == -1) {
                 ^~~~~~~~~~~~~~~~~~~
/root/rat_lite/src/ClientDriver.cpp:98:17: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/root/rat_lite/src/ClientDriver.cpp:105:31: error: ‘TJPF_RGBX’ was not declared in this scope
                               TJPF_RGBX, 2048 | TJFLAG_NOREALLOC) == -1) {
                               ^~~~~~~~~
/root/rat_lite/src/ClientDriver.cpp:105:49: error: ‘TJFLAG_NOREALLOC’ was not declared in this scope
                               TJPF_RGBX, 2048 | TJFLAG_NOREALLOC) == -1) {
                                                 ^~~~~~~~~~~~~~~~
/root/rat_lite/src/ClientDriver.cpp:104:17: error: there are no arguments to ‘tjDecompress2’ that depend on a template parameter, so a declaration of ‘tjDecompress2’ must be available [-fpermissive]
             if (tjDecompress2(jpegDecompressor, src, static_cast<unsigned long>(len), (unsigned char *)outputbuffer.data(), outwidth, 0, outheight,
                 ^~~~~~~~~~~~~
/root/rat_lite/src/ClientDriver.cpp: In instantiation of ‘void SL::RAT_Lite::ClientDriver::Frame(const unsigned char*, size_t, CALLBACKTYPE&&) [with CALLBACKTYPE = SL::RAT_Lite::ClientDriver::Build(const std::shared_ptr<SL::WS_LITE::IWSClient_Configuration>&)::<lambda(const std::shared_ptr<SL::WS_LITE::IWSocket>&, const SL::WS_LITE::WSMessage&)>::<lambda(const auto:2&, const auto:3&)>; size_t = long unsigned int]’:
/root/rat_lite/src/ClientDriver.cpp:159:131:   required from here
/root/rat_lite/src/ClientDriver.cpp:98:36: error: ‘tjDecompressHeader2’ was not declared in this scope
             if (tjDecompressHeader2(jpegDecompressor, src, static_cast<unsigned long>(len), &outwidth, &outheight, &jpegSubsamp) == -1) {
                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rat_lite/src/ClientDriver.cpp:98:36: note: suggested alternative: ‘tjDecompressHeader’
             if (tjDecompressHeader2(jpegDecompressor, src, static_cast<unsigned long>(len), &outwidth, &outheight, &jpegSubsamp) == -1) {
                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 tjDecompressHeader
/root/rat_lite/src/ClientDriver.cpp:105:65: error: ‘tjDecompress2’ was not declared in this scope
                               TJPF_RGBX, 2048 | TJFLAG_NOREALLOC) == -1) {
                                                                 ^
/root/rat_lite/src/ClientDriver.cpp:105:65: note: suggested alternative: ‘tjDecompress’
                               TJPF_RGBX, 2048 | TJFLAG_NOREALLOC) == -1) {
                                                                 ^
                                                                 tjDecompress
/root/rat_lite/src/ClientDriver.cpp: In instantiation of ‘void SL::RAT_Lite::ClientDriver::Frame(const unsigned char*, size_t, CALLBACKTYPE&&) [with CALLBACKTYPE = SL::RAT_Lite::ClientDriver::Build(const std::shared_ptr<SL::WS_LITE::IWSClient_Configuration>&)::<lambda(const std::shared_ptr<SL::WS_LITE::IWSocket>&, const SL::WS_LITE::WSMessage&)>::<lambda(const auto:4&, const auto:5&)>; size_t = long unsigned int]’:
/root/rat_lite/src/ClientDriver.cpp:164:127:   required from here
/root/rat_lite/src/ClientDriver.cpp:98:36: error: ‘tjDecompressHeader2’ was not declared in this scope
             if (tjDecompressHeader2(jpegDecompressor, src, static_cast<unsigned long>(len), &outwidth, &outheight, &jpegSubsamp) == -1) {
                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rat_lite/src/ClientDriver.cpp:98:36: note: suggested alternative: ‘tjDecompressHeader’
             if (tjDecompressHeader2(jpegDecompressor, src, static_cast<unsigned long>(len), &outwidth, &outheight, &jpegSubsamp) == -1) {
                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 tjDecompressHeader
/root/rat_lite/src/ClientDriver.cpp:105:65: error: ‘tjDecompress2’ was not declared in this scope
                               TJPF_RGBX, 2048 | TJFLAG_NOREALLOC) == -1) {
                                                                 ^
/root/rat_lite/src/ClientDriver.cpp:105:65: note: suggested alternative: ‘tjDecompress’
                               TJPF_RGBX, 2048 | TJFLAG_NOREALLOC) == -1) {
                                                                 ^
                                                                 tjDecompress
CMakeFiles/rat_lite.dir/build.make:62: recipe for target 'CMakeFiles/rat_lite.dir/src/ClientDriver.cpp.o' failed
make[2]: *** [CMakeFiles/rat_lite.dir/src/ClientDriver.cpp.o] Error 1
CMakeFiles/Makefile2:218: recipe for target 'CMakeFiles/rat_lite.dir/all' failed
make[1]: *** [CMakeFiles/rat_lite.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by smasherprog** [comment]
https://github.com/smasherprog/rat_lite/blob/master/README.md#libraries

**Comment by smasherprog** [comment]
I dont support old OS that do not use the latest builds of libraries

**Comment by ch3than** [comment]
I'm on Kali 2017.2 with latest cmake and nodejs and installed all libraries as u mentioned .it goes well till 78% and gets error message like above

**Comment by ch3than** [comment]
Did I miss anything to install ?? M I going wrong
