### ISSUE TITLE
client missing webpack.config.js?

### ISSUE THREAD

**Issue by boonkerz** [smasherprog/rat_lite#77]
> ratclient@0.0.0 webpack:watch /Users/thomas/projekte/Remote_Access_Library/src/client
> webpack --watch

No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! ratclient@0.0.0 webpack:watch: `webpack --watch`
npm ERR! Exit status 255

**Comment by smasherprog** [comment]
Should be fixed now on master
