### ISSUE TITLE
Request : How to use in c#

### ISSUE THREAD

**Issue by jigneshBadrakhiya** [smasherprog/rat_lite#80]
how to use in c#

**Comment by smasherprog** [comment]
You'll have to build the code, then get the dlls and use them in your c# project. I have been working on automatically generating dlls and libs for each release, but its not done yet.

**Comment by jigneshBadrakhiya** [comment]
but, how?

**Comment by smasherprog** [comment]
If you dont know how to integrate c++ and c#, then I cannot help you unfortunately. 
I would start with google and go from there.
