### ISSUE TITLE
Uncompileable on Windows

### ISSUE THREAD

**Issue by basketas** [smasherprog/rat_lite#81]
I am using Windows and Visual Studio 2013... Tried with v2012 as well.. Both x32 and x64 compilation, and versions of libraries..

This is my cmake command line for x64 compilation:

`cmake -DZLIB_INCLUDE_DIR="C:\zlib-master" -DZLIB_LIBRARY="C:\zlib-master\contrib\vstudio\vc12\x64\ZlibStatRelease" -DOPENSSL_ROOT_DIR="C:\OpenSSL-Windows-master\openssl-1.1.0e-vs2013" -DOPENSSL_INCLUDE_DIR="C:\OpenSSL-Windows-master\openssl-1.1.0e-vs2013\include64\openssl" -DOPENSSL_LIBRARIES="C:\OpenSSL-Windows-master\openssl-1.1.0e-vs2013\lib64" -DLIBJPEGTURBO_LIBRARIES="C:\libjpeg-turbo64\lib" -DLIBJPEGTURBO_INCLUDE_DIRS="C:\libjpeg-turbo64\include"
`

Errors such as these are shown when trying to build a VS solution generated by the CMAKE:
![image](https://user-images.githubusercontent.com/16399561/40087528-3e7b9598-58a3-11e8-9a07-00983a63c771.png)

or these:

![image](https://user-images.githubusercontent.com/16399561/40087582-7d476298-58a3-11e8-9a31-f7937c6d6114.png)

**Comment by smasherprog** [comment]
Ill take a look at this later today and get it fixed

**Comment by smasherprog** [comment]
I just tested this out with a clean build and I was successfull. 
I recommend using vcpkg instead of downloading everything manually. It should work then

**Comment by smasherprog** [comment]
closing due to lack of feedback. Let me know if using vcpckg helps.

**Comment by basketas** [comment]
Sorry for not responding, I've missed a notification that there was a reply on this thread. So, I've used vcpckg as you proposed and the libraries are not complaining:

![image](https://user-images.githubusercontent.com/16399561/42790056-0f861708-8969-11e8-919f-e4e84542b3e5.png)


But I still have compiling errors... Some of them are really strange such as: " **'npm' is not recognized as an internal or external command, operable program or batch file.**"

I ran the "VS Enterprise 2015 Update 3" with Administrator privileges. Clean solution was downloaded from github.

Since I noticed that there are some local includes missing, I checked the ALL BUILD Properties and this is how it looks like on my system (no additional include directories, although I am not sure if there should be any at all):

![image](https://user-images.githubusercontent.com/16399561/42790096-52dfce2c-8969-11e8-9d5a-7ce413ff4b6a.png)


And this is an entire BUILD log, so you can see the errors:
[error.txt](https://github.com/smasherprog/rat_lite/files/2199727/error.txt)
