### ISSUE TITLE
how to slove this error?

### ISSUE THREAD

**Issue by zhfnjust** [smasherprog/rat_lite#84]
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LIBJPEGTURBO (missing: LIBJPEGTURBO_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  modules/FindLIBJPEGTURBO.cmake:21 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:36 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/hh/git/rat_lite/CMakeFiles/CMakeOutput.log".

**Comment by smasherprog** [comment]
You need to install libjpeg turbo
https://github.com/smasherprog/rat_lite/wiki
