### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by leopucci** [smasherprog/rat_lite#85]
Hello @smasherprog. What a beautiful work you have done here. 
What are you doing these days? Commited to some projects? (just out of curiosity)

Could you help me understand how to build/run the android module?

**Comment by leopucci** [comment]
Really nice work. I see you spent more than 3 years on this. Is there anyone paying you to develop?
I would like to find someone that could fund me to learn boost, OO and image processing in the level that you are and do such a great job. This is just amazing. Have you done this all by yourself? bold move bro

**Comment by smasherprog** [comment]
This was a hobby project of mine. The android build doesnt work any more. 
Thanks

**Comment by leopucci** [comment]
Anytime. Thank you
